print("\033[31m", "=== Your aventure ===")
print("\033[0m", "You'll be asked many questions then we can make a wonderful story")
print()
name = input("Your name ")
enemy = input("Your worst enemy name ")
superpower = input("Your superpower ")
print()
print("Our story begins as our hero named", name)
print("aproaches a castle FULL of terror!")
print("suddenly a bolt of lightning STRIKES the ground right below", name)
print("'Our final battle begins!' shouts the evil", enemy, "clearely missing the fact that", name, "has the power of", superpower, "which means they'll win quite easily")
